spring:
  datasource:
    platform: postgres
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/project-management-system
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
