spring:
  datasource:
    platform: postgres
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/project-management-system
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_EMAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


app:
  jwt:
    key: ${SECRET_KEY}